version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: '/packages/ingestion'
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directories:
      - '/packages/ingestion'
      - '/packages/worker'
    schedule:
      interval: weekly
