import { existsSync, readFileSync, realpathSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { glob } from 'astro/loaders';
import type { Loader, LoaderContext, ParseDataOptions } from 'astro/loaders';

import { EDIT_BASE } from '../repo';

const PUBLIC_DOCS_FILES = [
  'install.md',
  'how-it-works.md',
  'quickstart/self-host.md',
  'guides/friction.md',
  'guides/github-app.md',
  'guides/source-maps.md',
  'guides/environments.md',
  'guides/slack-notifications.md',
  'guides/replay-privacy.md',
  'guides/source-map-privacy.md',
  'guides/api-keys.md',
  'guides/mcp.md',
  'architecture/precision.md',
  'architecture/trust.md',
  'reference/sdk-options.md',
  'reference/http-routes.md',
  'reference/reason-codes.md',
  'reference/environment-variables.md',
];

const PUBLIC_DOCS_PATHS = new Set(PUBLIC_DOCS_FILES);

export function isAllowedCanonicalPath(filePath: string): boolean {
  const normalized = filePath.replaceAll(path.sep, '/').replace(/^\.\//, '');
  return PUBLIC_DOCS_PATHS.has(normalized);
}

export function canonicalId(entry: string): string {
  return entry
    .replaceAll(path.sep, '/')
    .replace(/\.[^.]+$/, '')
    .split('/')
    .map((segment) =>
      segment
        .normalize('NFKD')
        .replace(/[\u0300-\u036f]/g, '')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, ''),
    )
    .join('/');
}

export function extractTitle(markdown: string, filePath = '<unknown>'): string {
  const headings: string[] = [];
  let fence: { marker: string; length: number } | undefined;

  for (const line of markdown.split(/\r?\n/)) {
    const fenceMatch = line.match(/^\s*(`{3,}|~{3,})/);
    if (fenceMatch?.[1]) {
      const marker = fenceMatch[1][0];
      if (!fence) {
        fence = { marker, length: fenceMatch[1].length };
      } else if (marker === fence.marker && fenceMatch[1].length >= fence.length) {
        fence = undefined;
      }
      continue;
    }

    if (fence) continue;

    const heading = line.match(/^#(?!#)\s+(.+?)\s*#*\s*$/)?.[1]?.trim();
    if (heading) headings.push(heading);
  }

  if (headings.length !== 1) {
    throw new Error(`${filePath} must contain exactly one level-one heading; found ${headings.length}.`);
  }

  return headings[0]!;
}

interface CompositeLoaderOptions {
  canonical: Loader;
  site: Loader;
  enrichCanonical?: DataEnricher;
  enrichSite?: DataEnricher;
}

type DataEnricher = <TData extends Record<string, unknown>>(
  props: ParseDataOptions<TData>,
  parseData: LoaderContext['parseData'],
) => Promise<TData>;

interface ScopedStore {
  store: LoaderContext['store'];
  size: () => number;
}

function scopedStore(
  target: LoaderContext['store'],
  owners: Map<string, string>,
  source: string,
): ScopedStore {
  const owned = new Set<string>();

  const store = new Proxy(target, {
    get(storeTarget, property, receiver) {
      if (property === 'keys') return () => owned.values();
      if (property === 'get') {
        return (id: string) => (owned.has(id) ? storeTarget.get(id) : undefined);
      }
      if (property === 'set') {
        return (entry: Parameters<LoaderContext['store']['set']>[0]) => {
          const owner = owners.get(entry.id);
          if (owner && owner !== source) {
            throw new Error(`Duplicate docs ID "${entry.id}" from ${owner} and ${source}.`);
          }
          const existing = owned.has(entry.id) ? storeTarget.get(entry.id) : undefined;
          if (existing?.filePath && entry.filePath && existing.filePath !== entry.filePath) {
            throw new Error(
              `Route collision: docs ID "${entry.id}" is generated by both ${existing.filePath} and ${entry.filePath}.`,
            );
          }
          owners.set(entry.id, source);
          owned.add(entry.id);
          return storeTarget.set(entry);
        };
      }
      if (property === 'delete') {
        return (id: string) => {
          if (!owned.delete(id)) return;
          owners.delete(id);
          return storeTarget.delete(id);
        };
      }
      if (property === 'clear') {
        return () => {
          for (const id of owned) {
            storeTarget.delete(id);
            owners.delete(id);
          }
          owned.clear();
        };
      }

      const value = Reflect.get(storeTarget, property, receiver) as unknown;
      return typeof value === 'function' ? value.bind(storeTarget) : value;
    },
  }) as LoaderContext['store'];

  return { store, size: () => owned.size };
}

export function composeDocsLoaders({
  canonical,
  site,
  enrichCanonical,
  enrichSite,
}: CompositeLoaderOptions): Loader {
  return {
    name: 'opslane-repo-docs',
    async load(context) {
      context.store.clear();
      const owners = new Map<string, string>();
      const canonicalStore = scopedStore(context.store, owners, 'canonical docs');
      const siteStore = scopedStore(context.store, owners, 'site content');

      await canonical.load({
        ...context,
        store: canonicalStore.store,
        parseData: enrichCanonical
          ? (props) => enrichCanonical(props, context.parseData)
          : context.parseData,
      });

      if (canonicalStore.size() === 0) {
        throw new Error('No canonical docs matched the public documentation allowlist.');
      }

      await site.load({
        ...context,
        store: siteStore.store,
        parseData: enrichSite ? (props) => enrichSite(props, context.parseData) : context.parseData,
      });

      if (siteStore.size() === 0) {
        throw new Error('No site-owned landing page was loaded.');
      }
    },
  };
}

export function createCanonicalEnricher(canonicalBase: string): DataEnricher {
  return async <TData extends Record<string, unknown>>(
    props: ParseDataOptions<TData>,
    parseData: LoaderContext['parseData'],
  ): Promise<TData> => {
    if (!props.filePath || !existsSync(props.filePath)) {
      throw new Error(`Canonical docs entry "${props.id}" has no readable source file.`);
    }

    // Resolve symlinks before the allowlist check: a committed symlink such as
    // docs/guides/x.md -> ../plans/secret.md must not publish excluded content.
    const realFilePath = realpathSync(props.filePath);
    const relativePath = path
      .relative(realpathSync(canonicalBase), realFilePath)
      .replaceAll(path.sep, '/');
    if (!isAllowedCanonicalPath(relativePath)) {
      throw new Error(`Canonical docs path is outside the public allowlist: ${relativePath}`);
    }

    Object.assign(props.data, {
      title: extractTitle(readFileSync(realFilePath, 'utf8'), realFilePath),
      slug: props.id,
      editUrl: `${EDIT_BASE}${relativePath}`,
    });

    return parseData(props);
  };
}

export function repoDocsLoader(): Loader {
  const canonical = glob({
    base: '../docs',
    pattern: PUBLIC_DOCS_FILES,
    generateId: ({ entry }) => canonicalId(entry),
  });
  const site = glob({
    base: './src/content/docs',
    pattern: 'index.mdx',
  });

  const canonicalBase = fileURLToPath(new URL('../../../docs/', import.meta.url));

  const enrichSite: DataEnricher = async <TData extends Record<string, unknown>>(
    props: ParseDataOptions<TData>,
    parseData: LoaderContext['parseData'],
  ): Promise<TData> => {
    Object.assign(props.data, { editUrl: false });
    return parseData(props);
  };

  return composeDocsLoaders({
    canonical,
    site,
    enrichCanonical: createCanonicalEnricher(canonicalBase),
    enrichSite,
  });
}
