"""Make provider_aggregation_key optional for alerts

Revision ID: 051cea711c7d
Revises: 5d6082fd095f
Create Date: 2024-07-17 11:24:47.768133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '051cea711c7d'
down_revision: Union[str, None] = '5d6082fd095f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert', 'provider_aggregation_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert', 'provider_aggregation_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
