"""Add integration model

Revision ID: 0e1f3c08ecae
Revises: dd0428013c18
Create Date: 2024-08-31 22:06:56.087002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e1f3c08ecae'
down_revision: Union[str, None] = 'dd0428013c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Enum('DATADOG', 'SENTRY', 'PAGERDUTY', name='integrationtype'), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('credential_schema', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_name'), 'integration', ['name'], unique=False)
    op.create_index(op.f('ix_integration_tenant_id'), 'integration', ['tenant_id'], unique=False)
    op.create_table('integrationcredential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_credentials', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrationcredential_tenant_id'), 'integrationcredential', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integrationcredential_tenant_id'), table_name='integrationcredential')
    op.drop_table('integrationcredential')
    op.drop_index(op.f('ix_integration_tenant_id'), table_name='integration')
    op.drop_index(op.f('ix_integration_name'), table_name='integration')
    op.drop_table('integration')
    # ### end Alembic commands ###
