"""Add noisy reason field to schema

Revision ID: 2bf739e402ba
Revises: ee95b7939fdc
Create Date: 2024-07-24 13:38:56.457866

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "2bf739e402ba"
down_revision: Union[str, None] = "ee95b7939fdc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alertconfiguration",
        sa.Column("noisy_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alertconfiguration", "noisy_reason")
    # ### end Alembic commands ###
