"""Add additional fields to alert model

Revision ID: 69c871db16b8
Revises: 535bd144955c
Create Date: 2024-06-21 12:51:58.718672

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "69c871db16b8"
down_revision: Union[str, None] = "535bd144955c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def create_enum(name, values, schema=None):
    """Helper function to create an enum type."""
    enum_type = sa.Enum(*values, name=name, create_type=False)
    if schema:
        enum_type = enum_type.schema(schema)
    enum_type.create(op.get_bind(), checkfirst=True)
    return enum_type


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alert_source_enum = create_enum("alertsource", ["DATADOG"])
    severity_level_enum = create_enum(
        "severitylevel", ["LOW", "MEDIUM", "HIGH", "CRITICAL"]
    )

    op.add_column(
        "alert", sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.add_column(
        "alert",
        sa.Column(
            "alert_source", sa.Enum("DATADOG", name="alertsource"), nullable=True
        ),
    )
    op.add_column("alert", sa.Column("tags", sa.JSON(), nullable=True))
    op.add_column("alert", sa.Column("additional_data", sa.JSON(), nullable=True))
    op.alter_column(
        "alert",
        "severity",
        existing_type=sa.VARCHAR(),
        type_=severity_level_enum,
        nullable=True,
        postgresql_using="severity::text::severitylevel",
    )
    op.create_index(op.f("ix_alert_status"), "alert", ["status"], unique=False)
    op.create_index(op.f("ix_alert_title"), "alert", ["title"], unique=False)
    op.drop_column("alert", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS alertsource;")
    op.execute("DROP TYPE IF EXISTS severitylevel;")

    op.add_column(
        "alert", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_alert_title"), table_name="alert")
    op.drop_index(op.f("ix_alert_status"), table_name="alert")
    op.alter_column(
        "alert",
        "severity",
        existing_type=sa.Enum(
            "LOW", "MEDIUM", "HIGH", "CRITICAL", name="severitylevel"
        ),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.drop_column("alert", "additional_data")
    op.drop_column("alert", "tags")
    op.drop_column("alert", "alert_source")
    op.drop_column("alert", "title")
    # ### end Alembic commands ###
