"""Add unique constraint on type

Revision ID: 6deb69d230bc
Revises: 7f18cdbae60e
Create Date: 2024-09-01 14:10:25.946024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6deb69d230bc'
down_revision: Union[str, None] = '7f18cdbae60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tenant_integration_type', 'integration', ['tenant_id', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant_integration_type', 'integration', type_='unique')
    # ### end Alembic commands ###
