"""Add integration credential foreign key to integration table

Revision ID: 7f18cdbae60e
Revises: 0e1f3c08ecae
Create Date: 2024-09-01 06:41:47.139383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f18cdbae60e'
down_revision: Union[str, None] = '0e1f3c08ecae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration', sa.Column('credential_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'integration', 'integrationcredential', ['credential_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integration', type_='foreignkey')
    op.drop_column('integration', 'credential_id')
    # ### end Alembic commands ###
