"""Add user_feedback column on alert table

Revision ID: 9968344692b6
Revises: 53daac222138
Create Date: 2024-08-25 13:17:56.476597

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "9968344692b6"
down_revision: Union[str, None] = "53daac222138"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alert", sa.Column("is_noisy", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alert", "is_noisy")
    # ### end Alembic commands ###
