"""Add datadog cycle key to Alerts model

Revision ID: e891afc144a9
Revises: 051cea711c7d
Create Date: 2024-07-17 14:23:01.121213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e891afc144a9'
down_revision: Union[str, None] = '051cea711c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('provider_cycle_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert', 'provider_cycle_key')
    # ### end Alembic commands ###
