// Generates src/mcp/skill-source.ts from the authored markdown so the skill
// compiles into dist/. The published tarball allows only dist/, package.json,
// README*, and LICENSE* (scripts/check-packed-packages.mjs), so shipping a
// skills/ directory would fail the release check.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, '..', 'skills', 'opslane', 'SKILL.md');
const target = join(here, '..', 'src', 'mcp', 'skill-source.ts');

const markdown = readFileSync(source, 'utf8');
mkdirSync(dirname(target), { recursive: true });
writeFileSync(
  target,
  `// GENERATED by scripts/embed-skill.mjs from skills/opslane/SKILL.md.\n` +
    `// Do not edit. Run "pnpm build" after changing the markdown.\n` +
    `export const SKILL_MD = ${JSON.stringify(markdown)};\n`,
  'utf8',
);
console.error(`embedded ${markdown.length} characters into src/mcp/skill-source.ts`);
