/**
 * Lightweight diff quality judge — runs after the agent produces a fix.
 * Uses Haiku to score scope, correctness, and preservation.
 * Used as the cascade trigger: if quality is poor, escalate to a stronger model.
 */
import type Anthropic from '@anthropic-ai/sdk';
import { createAnthropicClient } from '../anthropic-client.js';
import type { TokenUsage } from '../db.js';
import { usageFromResponse } from '../metered.js';

export interface DiffJudgeResult {
  scope: number;       // 0-2
  correctness: number; // 0-2
  preservation: number; // 0-2
  total: number;       // 0-6
  qualityPassed: boolean;
  explanation: string;
}

export const JUDGE_MODEL = 'claude-haiku-4-5-20251001';

const JUDGE_TOOL: Anthropic.Tool = {
  name: 'score_diff',
  description: 'Submit your quality assessment of the generated diff.',
  input_schema: {
    type: 'object' as const,
    properties: {
      scope: {
        type: 'number',
        description: '0 = changes unrelated files/code, 1 = slightly over-scoped but defensible, 2 = minimal and targeted',
      },
      correctness: {
        type: 'number',
        description: '0 = wrong root cause addressed, 1 = partially correct, 2 = addresses actual root cause',
      },
      preservation: {
        type: 'number',
        description: '0 = removes existing features/functionality, 1 = minor unnecessary removals, 2 = all existing behavior preserved',
      },
      explanation: {
        type: 'string',
        description: 'Brief rationale for scores (2-3 sentences)',
      },
    },
    required: ['scope', 'correctness', 'preservation', 'explanation'],
  },
};

export interface DiffJudgeInput {
  errorType: string;
  errorMessage: string;
  stackTrace: string;
  diff: string;
  stackTraceFiles: string[];
  frictionEvidence?: string;
}

export async function judgeDiff(
  apiKey: string,
  input: DiffJudgeInput,
  onUsage?: (usage: TokenUsage) => void,
): Promise<DiffJudgeResult> {
  const client = createAnthropicClient(apiKey);

  const prompt = `You are evaluating a code diff generated by an AI agent that was asked to fix a production error.

Your job is to assess diff QUALITY. A diff can fix the bug but still be low quality if it:
- Modifies files or code unrelated to the bug
- Removes existing features, test IDs, or SDK integrations
- Comments out working code instead of leaving it alone
- Replaces function implementations with no-ops when they weren't the cause

Evaluate objectively. Score the diff using the score_diff tool.

## Error Being Fixed
Type: ${input.errorType}
Message: ${input.errorMessage}

Stack Trace:
<untrusted_data>
${input.stackTrace.slice(0, 3000)}
</untrusted_data>

Files referenced in stack trace: ${input.stackTraceFiles.join(', ') || 'none detected'}

${input.frictionEvidence ? `## Friction Evidence (what the user experienced)
<untrusted_data>
${input.frictionEvidence.slice(0, 5000)}
</untrusted_data>
` : ''}

## Agent's Generated Diff
<untrusted_data>
${input.diff.slice(0, 10000)}
</untrusted_data>`;

  const response = await client.messages.create({
    model: JUDGE_MODEL,
    max_tokens: 1024,
    messages: [{ role: 'user', content: prompt }],
    tools: [JUDGE_TOOL],
    tool_choice: { type: 'tool', name: 'score_diff' },
  });
  // Report immediately: parsing below can reject a response that was paid for.
  onUsage?.(usageFromResponse(response));

  const toolUse = response.content.find(b => b.type === 'tool_use');
  if (!toolUse || toolUse.type !== 'tool_use') {
    throw new Error('Judge returned no tool_use block');
  }

  const raw = toolUse.input as Record<string, unknown>;
  if (typeof raw.scope !== 'number' || typeof raw.correctness !== 'number' || typeof raw.preservation !== 'number') {
    throw new Error(`Judge returned invalid scores: scope=${raw.scope}, correctness=${raw.correctness}, preservation=${raw.preservation}`);
  }

  const scope = Math.max(0, Math.min(2, Math.round(raw.scope)));
  const correctness = Math.max(0, Math.min(2, Math.round(raw.correctness)));
  const preservation = Math.max(0, Math.min(2, Math.round(raw.preservation)));
  const explanation = typeof raw.explanation === 'string' ? raw.explanation : '';
  const total = scope + correctness + preservation;
  const qualityPassed = total >= 4 && scope >= 1 && correctness >= 1 && preservation >= 1;

  return { scope, correctness, preservation, total, qualityPassed, explanation };
}
